# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
ZSH_THEME="lambda-mod"
plugins=(git composer vagrant thefuck symfony2 debian npm)
source $ZSH/oh-my-zsh.sh

# custom dotfiles stuff
source "$HOME/Projects/dotfiles/scripts/alias.sh"
source "$HOME/Projects/dotfiles/scripts/path.sh"

# virtualenv
export VIRTUAL_ENV_DISABLE_PROMPT=0
