# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# ZSH configuration
ZSH_THEME="lambda-mod"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

plugins=(git composer vagrant thefuck symfony2 ubuntu npm
  gem bundler rake pip grunt gulp gpg-agent docker docker-compose
  cp capistrano zsh-syntax-highlighting  bower cp common-aliases
  scala sudo)

source $ZSH/oh-my-zsh.sh

# custom $PATH variable
export PATH=$PATH:$HOME/Projects/dotfiles/bin

# a collection of useful shell aliases.
# used for shell env and short dir jumping
source ~/Projects/dotfiles/zsh/scripts/alias.sh

# private settings
source ~/Projects/dotfiles/zsh/scripts/private.sh
