# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
ZSH_THEME="lambda-mod"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

plugins=(git composer vagrant thefuck symfony2 debian npm
  gem bundler rake pip grunt gulp gpg-agent docker docker-compose
  cp capistrano zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# custom $PATH variable
export PATH=$PATH:$HOME/Projects/dotfiles/bin

# a collection of useful shell aliases.
# used for shell env and short dir jumping

source ~/Projects/dotfiles/zsh/scripts/private.sh

alias ~="cd ~"
alias proj="cd ~/Projects"

alias rb="ruby"
alias py="python"
alias cls="clear screen"
alias sl="ll"
alias ll="ls -la"

alias phi="php -a"
alias p="php"

alias ni="npm install"
alias nis="npm install --save"
alias nid="npm install --save-dev"
alias nig="npm install -g"

alias mkdirp="mkdir -p"

alias rbs="bundle exec rake spec"
alias rbt="bundle exec rake test"
alias npt="npm test"
alias plt="bin/activator test" # scala play activator
alias put="bin/phpunit"
alias bht="bin/behat -f progress --no-snippets"

alias dotf="cd ~/Projects/dotfiles"
alias apik="cd ~/Projects/Ma27ApiKeyAuthenticationBundle"
alias sent="cd ~/Projects/Sententiaregum"
alias eslv="cd ~/Projects/eslint-plugin-varspacing"
alias dtvm="cd ~/Projects/deployment-test-vm"
alias ppmd="cd ~/Projects/puppet-module-devel"
alias ppnd="cd ~/Projects/puppet-module-devel/dev/nodejs"
alias ppcp="cd ~/Projects/puppet-module-devel/dev/composer"

alias docs="cd ~/Documents"
alias pics="cd ~/Pictures"
alias dwnl="cd ~/Downloads"

# credits to http://askubuntu.com/questions/365965/how-to-remove-all-rc-residual-packages-using-command-line-at-once
alias remove_rc_pkgs="sudo apt-get remove --purge $(dpkg -l | grep "^rc" | awk '{print $2}' | tr '\n' ' ')"
